empolye/emp_app/urls.py
from django.contrib import admin
from django.urls import path
from .import views
app_name="emp_app"

urlpatterns = [
    path('',views.home,name='home'),
    path('view/',views.get_empolye,name='view'),
    path('add/', views.add_empolye, name='add'),
    path('update/<int:pk>', views.update_employe, name='update'),
    path('delete/<int:pk>', views.delete, name='delete'),
    path('register', views.register, name='register'),
    path('login', views.user_login, name='login'),
    path('logout', views.user_logout, name='logout'),

]

empolye/empolye/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('emp_app.urls'))
]

empolye/emp_app/models.py
from django.db import models

# Create your models here.

class Empolye(models.Model):
    emp_id=models.IntegerField()
    name=models.CharField(max_length=20)
    age=models.IntegerField()
    salary=models.IntegerField()

    def __str__(self):
        return self.name

empolye/emp_app/forms.py
from  django import forms
from .models import Empolye

class EmpForm(forms.ModelForm):
    class Meta:
        model=Empolye
        fields='__all__'

empolye/emp_app/views.py
from django.shortcuts import render
from .models import Empolye
from .forms import EmpForm
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.contrib.auth import  authenticate,login,logout
from django.contrib.auth.decorators import login_required
# Create your views here.


def home(request):
    return render(request,'home.html')

def get_empolye(request):
    emp=Empolye.objects.all()
    return render(request,'view.html',{'emp':emp})

@login_required
def add_empolye(request):
    if (request.POST):
        form=EmpForm(request.POST)
        if form.is_valid():
            form.save()
            return get_empolye(request)
    else:
        form=EmpForm()
    return render(request,'add.html',{'form':form})

@login_required
def update_employe(request,pk):
    e=Empolye.objects.get(id=pk)
    if(request.POST):
        form=EmpForm(request.POST,instance=e)
        if form.is_valid():
            form.save()
            return get_empolye(request)
    else:
        form=EmpForm(instance=e)
    return render(request,'add.html',{'form':form})

@login_required
def delete(request,pk):
    e=Empolye.objects.get(id=pk)
    e.delete()
    return home(request)

def register(request):
    if request.POST:
        username=request.POST['username']
        email = request.POST['email']
        password=request.POST['password']
        cp = request.POST['cp']

        if(password == cp):
            u=User.objects.create_user(username=username,email=email,password=password)
            u.save()
            return user_login(request)
        else:
            return  HttpResponse("password are not same")
    return render(request,'register.html')

def user_login(request):
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']
        user=authenticate(username=username,password=password)
        if user:
            login(request,user)
            return home(request)
        else:
            return HttpResponse("invalid password or username")
    return render(request,'login.html')

@login_required
def user_logout(request):
    logout(request)
    return user_login(request)

empolye/templates/add.html
{% extends 'base.html'%}
{% block content%}
<h2>Add Employee Here...</h2>

<form method="post">
    {% csrf_token %}

    {{form.as_p}}

    <button type="submit">submit</button>

</form>
{% endblock content%}

empolye/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Empolye APP</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'emp_app:home' %}">Home</a>
        </li>


        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'emp_app:view' %}">view</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'emp_app:add' %}">add</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'emp_app:logout' %}">Logout</a>
        </li>
        {%else%}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'emp_app:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'emp_app:login' %}">Login</a>
        </li>

        {% endif %}



      </ul>
    </div>
  </div>
</nav>

{% block content %}


{% endblock content %}

</body>
</html>

empolye/templates/home.html
{% extends 'base.html'%}
{% load static %}
{% block content%}
<body style="background-image:url('{% static "images/original.png"%}');background-size:cover;">
<h2 style="text-align:center">Welcome To Empolyee App</h2>
</body>
{% endblock content%}

empolye/templates/login.html
{% extends 'base.html' %}
{% block content %}
<form class="form" method="post">
    {% csrf_token %}
    <p class="form-title fw-bold">Login</p>
    <div class="input-container">
        <input type="text" placeholder="username" name="username">
    </div>
    <div class="input-container">
        <input type="password" placeholder="password" name="password">
    </div>

    <button type="submit" class="submit">Login</button>
</form>

{% endblock content %}

empolye/templates/register.html
{% extends 'base.html' %}
{% block content %}
<form class="form" method="post">
    {% csrf_token %}
    <p class="form-title fw-bold">Register</p>
    <div class="input-container">
        <input type="text" placeholder="username" name="username">
    </div>
    <div class="input-container">
        <input type="email" placeholder="Email" name="email">
    </div>
    <div class="input-container">
        <input type="password" placeholder="password" name="password">
    </div>
    <div class="input-container">
        <input type="password" placeholder="Confirm password" name="cp">
    </div>

    <button type="submit" class="submit">Sign up</button>
</form>

{% endblock content %}

empolye/templates/view.html
{% extends 'base.html'%}
{% block content%}
<h2>View Employee List</h2>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Emp.ID</th>
      <th>Name</th>
      <th>Age</th>
      <th>Salary</th>
      <th>Update</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
  {% for i in emp %}
    <tr>
      <th>{{i.emp_id}}</th>
      <td>{{i.name}}</td>
      <td>{{i.age}}</td>
      <td>{{i.salary}}</td>
      <td><a href="{% url 'emp_app:update' i.id %}" class="btn btn-primary">Update</a></td>
      <td><a href="{% url 'emp_app:delete' i.id %}" class="btn btn-danger">Delete</a></td>
    </tr>
  {% endfor %}
  </tbody>
</table>

{% endblock content%}